services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - /opt/appdata/apps/ollama:/root/.ollama
    ports:
      - 11434:11434
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - OLLAMA_VULKAN=1
    restart: unless-stopped
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - 8080:8080
    volumes:
      - /opt/appdata/openwebui/data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped

